env = Environment(CCFLAGS='-O3 -std=gnu++0x -ggdb -DUSE_MATH=1 -Wno-write-strings')
target = ARGUMENTS.get('TARGET','LINUX')

if target=='LINUX':
   env.Append(LIBS = ['glut', 'GL', 'png', 'pthread', 'dl'])
   env.Append(CCFLAGS=' -DFLX_LINUX')
   env.Append(CPPPATH = '.')

if target=='RPI':
   # raspberry pi
   env.Append(LIBS = ['glutes', 'GLESv1_CM', 'EGL', 'bcm_host', 'X11', 'png'])
   env.Append(CCFLAGS=' -DFLX_RPI -fpermissive')
   env.Append(CPPPATH = '/opt/vc/include:.')
   env.Append(LIBPATH = '/opt/vc/lib')

env.Program( target = 'app',
             source = ['main.cpp',
                       'core/list.cpp',
                       'core/db.cpp',
                       'core/db_container.cpp',
                       'core/idmap.cpp',
                       'sqlite/sqlite3.c',
                       'scheme/scheme.cpp'
                       ] )
